"use client";

import { FormEvent, Suspense, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { AlertCircle, Plane, RefreshCw } from "lucide-react";
import CheckoutPanel from "@/app/components/seats/CheckoutPanel";
import LedgerPanel, { BookingSuccessBanner } from "@/app/components/seats/LedgerPanel";
import SeatMap from "@/app/components/seats/SeatMap";
import type { FlightInfo, Seat, SeatClass } from "@/app/components/seats/seatMapUtils";
import { normalizeLedgerPayload, type Ledger, type Promotion } from "@/app/components/seats/types";
import Button from "@/app/components/ui/Button";
import { cn } from "@/lib/cn";

const t = {
  title: "Choose your seat",
  subtitle: "Select an available seat on the map, then complete checkout.",
  flightId: "Flight ID",
  load: "Reload seats",
  leg: "Leg",
  connectingNotice: "Connecting itinerary — choose one seat for each leg.",
  payment: "Payment",
  selectedSeat: "Selected seat",
  none: "Tap a seat on the map",
  reserve: "Confirm booking",
  checkout: "Confirm all legs",
  cancelRefund: "Cancel & refund",
  lookup: "Load ledger",
  lookupBooking: "Booking ID",
  autoIds: "IDs are generated by the server on checkout.",
  promos: "Promotions",
  noPromos: "No promotions for this seat.",
  applyNone: "No promotion",
  estimated: "Estimated total",
  held: "held for 10 minutes.",
  selectFirst: "Please select a seat before checkout.",
  selectAllLegs: "Please choose seats for every leg.",
  reserveError: "An error occurred while creating the booking.",
  reserved: "Your booking is confirmed!",
  reservedDetail: "Payment completed. Details are shown below.",
  refunded: "Refund processed.",
  conflictTitle: "Seat unavailable",
  confirm: "Got it",
  loading: "Loading seat map…",
  available: "Available",
  heldLabel: "Held",
  reservedLabel: "Taken",
  unavailable: "This seat is not available.",
  exit: "Exit",
  galley: "Galley",
  ledger: "Payment ledger",
  noLedger: "No ledger loaded. Complete a booking or enter a booking ID above.",
  selectedOnly: "Seat selected — confirm below to hold and book.",
  classNames: { Economy: "Economy", Business: "Business", First: "First" } as Record<SeatClass, string>,
  myBookings: "View all my bookings"
};

function makeId() {
  return Math.floor(Date.now() % 1_000_000_000);
}

function bookingIdFromReserveResponse(data: unknown): number | null {
  if (!data || typeof data !== "object") return null;
  const record = data as Record<string, unknown>;
  if (typeof record.booking_id === "number") return record.booking_id;
  if (Array.isArray(record.bookings) && record.bookings.length > 0) {
    const last = record.bookings.at(-1) as { booking_id?: number } | undefined;
    return typeof last?.booking_id === "number" ? last.booking_id : null;
  }
  return null;
}

function SeatsContent() {
  const params = useSearchParams();
  const initialFlightIds = (params.get("flight_ids") ?? params.get("flight_id") ?? "1001")
    .split(",")
    .map((value) => value.trim())
    .filter(Boolean);
  const [flightIds, setFlightIds] = useState(initialFlightIds);
  const [activeLegIndex, setActiveLegIndex] = useState(0);
  const activeFlightId = flightIds[activeLegIndex] ?? "1001";
  const [flight, setFlight] = useState<FlightInfo | null>(null);
  const [seats, setSeats] = useState<Seat[]>([]);
  const [selected, setSelected] = useState<Seat | null>(null);
  const [selectedByFlight, setSelectedByFlight] = useState<Record<string, Seat>>({});
  const [selectedPromoByFlight, setSelectedPromoByFlight] = useState<Record<string, string>>({});
  const [promoDiscountByFlight, setPromoDiscountByFlight] = useState<Record<string, number>>({});
  const [message, setMessage] = useState("");
  const [alert, setAlert] = useState("");
  const [ledger, setLedger] = useState<Ledger | null>(null);
  const [promotions, setPromotions] = useState<Promotion[]>([]);
  const [form, setForm] = useState({ payment_method: "CARD", lookup_booking_id: "" });
  const [bookingSuccess, setBookingSuccess] = useState<{ bookingId: string; seatLabel: string } | null>(null);

  const sections = useMemo(
    () =>
      (["First", "Business", "Economy"] as SeatClass[])
        .map((className) => ({ className, seats: seats.filter((seat) => seat.class_name === className) }))
        .filter((section) => section.seats.length > 0),
    [seats]
  );

  const seatStats = useMemo(() => {
    const available = seats.filter((s) => s.seat_status === "available").length;
    return { available, total: seats.length };
  }, [seats]);

  async function loadSeats(targetFlightId = activeFlightId) {
    await fetch("/api/flights/hold/release", { method: "POST" });
    const response = await fetch(`/api/flights/seats?flight_id=${targetFlightId}`);
    const json = await response.json();
    setFlight(json.data?.flight ?? null);
    setSeats(json.data?.seats ?? []);
  }

  async function loadLedger(bookingId = form.lookup_booking_id) {
    if (!bookingId) return;
    const response = await fetch(`/api/bookings/ledger?booking_id=${bookingId}`);
    const json = await response.json();
    if (!response.ok || !json.success) {
      setLedger(null);
      return;
    }
    setLedger(normalizeLedgerPayload(json.data));
  }

  const selectedPromo = selectedPromoByFlight[activeFlightId] ?? "";

  const connectingEstimatedTotal = useMemo(() => {
    return flightIds.reduce((sum, id) => {
      const seat = selectedByFlight[id];
      if (!seat) return sum;
      const discount = promoDiscountByFlight[id] ?? 0;
      return sum + seat.price * (1 - discount / 100);
    }, 0);
  }, [flightIds, selectedByFlight, promoDiscountByFlight]);

  async function loadPromotions(seat: Seat) {
    const query = new URLSearchParams({
      flight_id: String(seat.flight_id),
      class_name: seat.class_name
    });
    const response = await fetch(`/api/flights/promotions?${query}`);
    const json = await response.json();
    setPromotions(json.data?.promotions ?? []);
  }

  function handlePromoChange(code: string) {
    setSelectedPromoByFlight((prev) => ({ ...prev, [activeFlightId]: code }));
    const discount = promotions.find((promo) => promo.promo_code === code)?.discount_percent ?? 0;
    setPromoDiscountByFlight((prev) => {
      const next = { ...prev };
      if (code && discount > 0) next[activeFlightId] = discount;
      else delete next[activeFlightId];
      return next;
    });
  }

  useEffect(() => {
    loadSeats();
  }, []);

  async function switchLeg(index: number) {
    const nextFlightId = flightIds[index];
    setActiveLegIndex(index);
    const seat = selectedByFlight[nextFlightId] ?? null;
    setSelected(seat);
    setPromotions([]);
    await loadSeats(nextFlightId);
    if (seat) await loadPromotions(seat);
  }

  function chooseSeat(seat: Seat) {
    setBookingSuccess(null);
    setSelected(seat);
    setSelectedByFlight((prev) => ({ ...prev, [String(seat.flight_id)]: seat }));
    setMessage(t.selectedOnly);
    loadPromotions(seat);
  }

  async function holdSelectedSeat(seat: Seat) {
    const response = await fetch("/api/flights/hold", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ hold_id: makeId(), flight_id: seat.flight_id, seat_number: seat.seat_number })
    });
    const json = await response.json();
    if (response.status === 409) {
      setAlert(json.message ?? "The selected seat is already held or reserved.");
      await loadSeats(String(seat.flight_id));
      return false;
    }
    setMessage(`${seat.seat_number} ${t.held}`);
    await loadSeats(String(seat.flight_id));
    return true;
  }

  async function reserve(event: FormEvent) {
    event.preventDefault();
    if (!selected) {
      setAlert(t.selectFirst);
      return;
    }
    const seatsToReserve = flightIds.map((id) => selectedByFlight[id]).filter(Boolean);
    if (seatsToReserve.length !== flightIds.length) {
      setAlert(t.selectAllLegs);
      return;
    }

    const legsForCheckout = [];
    for (const seat of seatsToReserve) {
      const held = await holdSelectedSeat(seat);
      if (!held) return;
      legsForCheckout.push({
        flight_id: seat.flight_id,
        seat_number: seat.seat_number,
        promo_code: selectedPromoByFlight[String(seat.flight_id)] || undefined
      });
    }

    const response = await fetch("/api/bookings/reserve-itinerary", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ payment_method: form.payment_method, legs: legsForCheckout })
    });
    const json = await response.json();
    if (response.status === 409) {
      setAlert(json.message ?? "One of the selected seats is already held or reserved.");
      await loadSeats();
      return;
    }
    if (!response.ok || !json.success) {
      setAlert(json.message ?? t.reserveError);
      return;
    }

    const bookingId = bookingIdFromReserveResponse(json.data);
    if (bookingId == null) {
      setAlert(t.reserveError);
      return;
    }
    const lastBookingId = String(bookingId);
    const bookedSeats = seatsToReserve.map((s) => s.seat_number).join(", ");
    setBookingSuccess({ bookingId: lastBookingId, seatLabel: bookedSeats });
    setMessage(`${t.reserved} Booking #${lastBookingId} · Seat ${bookedSeats}`);
    setForm((prev) => ({ ...prev, lookup_booking_id: lastBookingId }));
    setSelected(null);
    setSelectedByFlight({});
    setSelectedPromoByFlight({});
    setPromoDiscountByFlight({});
    setPromotions([]);
    await loadSeats();
    await loadLedger(lastBookingId);
  }

  async function cancelAndRefund() {
    const response = await fetch("/api/bookings/cancel", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ booking_id: Number(form.lookup_booking_id) })
    });
    const json = await response.json();
    if (!response.ok) {
      setAlert(json.message ?? t.reserveError);
      return;
    }
    setMessage(t.refunded);
    await loadSeats();
    await loadLedger(form.lookup_booking_id);
  }

  return (
    <div className="space-y-6">
      {alert && (
        <div className="fixed inset-0 z-50 grid place-items-center bg-zinc-900/40 px-4 backdrop-blur-sm">
          <div className="w-full max-w-md rounded-2xl border border-red-100 bg-white p-6 shadow-xl">
            <div className="flex items-start gap-3">
              <div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-red-50 text-red-600">
                <AlertCircle className="size-5" strokeWidth={1.75} />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-zinc-900">{t.conflictTitle}</h2>
                <p className="mt-2 text-sm leading-relaxed text-zinc-600">{alert}</p>
              </div>
            </div>
            <Button onClick={() => setAlert("")} className="mt-5 w-full bg-red-600 hover:bg-red-700">
              {t.confirm}
            </Button>
          </div>
        </div>
      )}

      <section className="rounded-2xl border border-zinc-100 bg-white p-5 shadow-sm sm:p-6">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="min-w-0 flex-1">
            <p className="text-xs font-semibold uppercase tracking-wider text-cerulean-700">Seat selection</p>
            <h1 className="mt-1 text-2xl font-bold tracking-tight text-zinc-900 sm:text-3xl">{t.title}</h1>
            <p className="mt-1 text-sm text-zinc-500">{t.subtitle}</p>
            {flight && (
              <div className="mt-4 inline-flex flex-wrap items-center gap-2 rounded-xl bg-zinc-50 px-4 py-3 text-sm">
                <Plane className="size-4 text-cerulean-700" strokeWidth={1.75} />
                <span className="font-semibold text-zinc-900">
                  {flight.airline_name} {flight.flight_number}
                </span>
                <span className="text-zinc-400">·</span>
                <span className="font-medium text-zinc-700">
                  {flight.dep_airport} → {flight.arr_airport}
                </span>
                <span className="text-zinc-400">·</span>
                <span className="text-zinc-500">{flight.model}</span>
              </div>
            )}
          </div>
          <div className="flex flex-wrap items-end gap-2">
            <label className="text-xs font-medium text-zinc-500">
              {t.flightId}
              <input
                value={activeFlightId}
                onChange={(event) => {
                  const next = event.target.value;
                  setFlightIds([next]);
                  setActiveLegIndex(0);
                }}
                className="mt-1 block w-24 rounded-lg border border-zinc-200 px-3 py-2 text-sm outline-none focus:border-cerulean-500"
              />
            </label>
            <Button type="button" variant="outline" size="sm" onClick={() => loadSeats()} className="gap-1.5">
              <RefreshCw className="size-3.5" strokeWidth={1.75} />
              {t.load}
            </Button>
          </div>
        </div>

        {flightIds.length > 1 && (
          <div className="mt-5 flex flex-wrap gap-2">
            {flightIds.map((id, index) => (
              <button
                key={id}
                type="button"
                onClick={() => switchLeg(index)}
                className={cn(
                  "rounded-full px-4 py-2 text-sm font-semibold transition",
                  activeLegIndex === index
                    ? "bg-deep-space-blue text-white shadow-sm"
                    : "border border-zinc-200 bg-white text-zinc-700 hover:border-zinc-300"
                )}
              >
                {t.leg} {index + 1}: {id}
                {selectedByFlight[id] ? ` · ${selectedByFlight[id].seat_number}` : ""}
                {selectedPromoByFlight[id] ? ` · ${selectedPromoByFlight[id]}` : ""}
              </button>
            ))}
          </div>
        )}

        <div className="mt-5 flex flex-wrap items-center gap-3 border-t border-zinc-100 pt-4">
          {flightIds.length > 1 && <span className="text-xs font-medium text-cerulean-700">{t.connectingNotice}</span>}
          <span className="inline-flex items-center gap-2 text-xs text-zinc-600">
            <span className="size-3 rounded border border-zinc-200 bg-white shadow-sm" /> {t.available}
          </span>
          <span className="inline-flex items-center gap-2 text-xs text-zinc-600">
            <span className="size-3 rounded border border-amber-200 bg-amber-50" /> {t.heldLabel}
          </span>
          <span className="inline-flex items-center gap-2 text-xs text-zinc-600">
            <span className="size-3 rounded border border-zinc-200 bg-zinc-100" /> {t.reservedLabel}
          </span>
          <span className="text-xs text-zinc-400">
            {seatStats.available} / {seatStats.total} available
          </span>
          {message && (
            <span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-800">{message}</span>
          )}
        </div>
      </section>

      <div className="grid gap-6 lg:grid-cols-[1fr_360px] xl:grid-cols-[1fr_380px]">
        <SeatMap
          flight={flight}
          sections={sections}
          selected={selected}
          onSelect={chooseSeat}
          labels={{
            available: t.available,
            held: t.heldLabel,
            reserved: t.reservedLabel,
            unavailable: t.unavailable,
            exit: t.exit,
            galley: t.galley,
            classNames: t.classNames
          }}
        />

        <div className="space-y-4 lg:sticky lg:top-24 lg:self-start">
          {bookingSuccess && (
            <BookingSuccessBanner
              bookingId={bookingSuccess.bookingId}
              seatLabel={bookingSuccess.seatLabel}
              onDismiss={() => setBookingSuccess(null)}
              viewBookingsLabel={t.myBookings}
            />
          )}

          <CheckoutPanel
            selected={selected}
            flightIds={flightIds}
            selectedByFlight={selectedByFlight}
            promotions={promotions}
            selectedPromo={selectedPromo}
            connectingEstimatedTotal={connectingEstimatedTotal}
            promoDiscountByFlight={promoDiscountByFlight}
            paymentMethod={form.payment_method}
            lookupBookingId={form.lookup_booking_id}
            labels={{
              payment: t.payment,
              selectedSeat: t.selectedSeat,
              none: t.none,
              promos: t.promos,
              noPromos: t.noPromos,
              applyNone: t.applyNone,
              estimated: t.estimated,
              lookupBooking: t.lookupBooking,
              autoIds: t.autoIds,
              reserve: t.reserve,
              checkout: t.checkout,
              cancelRefund: t.cancelRefund,
              lookup: t.lookup,
              myBookings: t.myBookings
            }}
            onPromoChange={handlePromoChange}
            onPaymentMethodChange={(method) => setForm((prev) => ({ ...prev, payment_method: method }))}
            onLookupBookingIdChange={(id) => setForm((prev) => ({ ...prev, lookup_booking_id: id }))}
            onReserve={reserve}
            onCancelRefund={cancelAndRefund}
            onLoadLedger={() => loadLedger()}
          />

          <LedgerPanel ledger={ledger} emptyLabel={t.noLedger} />
        </div>
      </div>
    </div>
  );
}

export default function SeatsPage() {
  return (
    <Suspense
      fallback={
        <div className="rounded-2xl border border-zinc-100 bg-white p-8 text-center text-sm text-zinc-500">
          {t.loading}
        </div>
      }
    >
      <SeatsContent />
    </Suspense>
  );
}
