"use client";

import { FormEvent, Suspense, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useLocale } from "@/lib/useLocale";

type SeatStatus = "available" | "held" | "reserved";
type SeatClass = "Economy" | "Business" | "First";

type Seat = {
  flight_id: number;
  seat_number: string;
  class_name: SeatClass;
  price: number;
  seat_status: SeatStatus;
};

type FlightInfo = {
  flight_id: number;
  model: string;
  airline_name: string;
  flight_number: string;
  dep_airport: string;
  arr_airport: string;
};

type Ledger = {
  booking: null | {
    booking_id: number;
    user_id: string;
    flight_id: number;
    seat_number: string;
    ticket_id: number;
    payment_id: number;
    amount: number;
    payment_method: string;
    payment_status: string;
    status: string;
  };
  refunds: Array<{
    refund_id: number;
    payment_id: number;
    refund_amount: number;
    refund_time: string;
  }>;
};

type Promotion = {
  promo_code: string;
  description: string;
  discount_percent: number;
};

const copy = {
  ko: {
    title: "실제 기체형 좌석 배치도",
    flightId: "항공편 ID",
    load: "좌석 조회",
    leg: "구간",
    connectingNotice: "경유 여정은 각 구간별 좌석을 하나씩 선택해야 합니다.",
    payment: "결제/환불",
    selectedSeat: "선택 좌석",
    none: "없음",
    reserve: "DB 결제 생성",
    checkout: "모든 구간 결제 생성",
    cancelRefund: "예약 취소 및 환불 생성",
    lookup: "결제 내역 조회",
    lookupBooking: "조회/환불 예약 ID",
    autoIds: "Booking/Ticket/Payment/Refund ID는 서버에서 자동 발급됩니다.",
    promos: "적용 가능한 프로모션",
    noPromos: "선택한 좌석에 적용 가능한 프로모션이 없습니다.",
    applyNone: "적용 안 함",
    estimated: "예상 결제 금액",
    held: "좌석을 10분간 홀드했습니다.",
    selectFirst: "결제할 좌석을 먼저 선택해 주세요.",
    selectAllLegs: "모든 구간의 좌석을 선택해 주세요.",
    reserveError: "결제 처리 중 오류가 발생했습니다.",
    reserved: "결제 및 예약 레코드가 생성되었습니다.",
    refunded: "환불 레코드가 생성되었습니다.",
    conflictTitle: "좌석 충돌",
    confirm: "확인",
    loading: "좌석 정보를 불러오는 중입니다.",
    available: "선택 가능",
    heldLabel: "홀드 중",
    reservedLabel: "예약 완료",
    unavailable: "이미 선택된 좌석입니다.",
    exit: "비상구",
    galley: "갤리",
    ledger: "DB 결제/환불 내역",
    noLedger: "조회된 결제 내역이 없습니다.",
    selectedOnly: "좌석을 선택했습니다. DB 결제 생성 버튼을 누르면 좌석 홀드와 예약이 함께 처리됩니다.",
    classNames: { Economy: "이코노미", Business: "비즈니스", First: "퍼스트" }
  },
  en: {
    title: "Aircraft-Style Seat Map",
    flightId: "Flight ID",
    load: "Load Seats",
    leg: "Leg",
    connectingNotice: "For connecting itineraries, choose one seat for each leg.",
    payment: "Payment / Refund",
    selectedSeat: "Selected Seat",
    none: "None",
    reserve: "Create DB Payment",
    checkout: "Create Payment for All Legs",
    cancelRefund: "Cancel and Create Refund",
    lookup: "Load Payment Ledger",
    lookupBooking: "Booking ID for Lookup / Refund",
    autoIds: "Booking, ticket, payment, and refund IDs are generated by the server.",
    promos: "Available Promotions",
    noPromos: "No promotions are available for this selected seat.",
    applyNone: "No promotion",
    estimated: "Estimated Payment",
    held: "has been held for 10 minutes.",
    selectFirst: "Please select a seat before payment.",
    selectAllLegs: "Please choose seats for every leg.",
    reserveError: "An error occurred while creating payment.",
    reserved: "Payment and reservation records have been created.",
    refunded: "Refund record has been created.",
    conflictTitle: "Seat Conflict",
    confirm: "OK",
    loading: "Loading seat information.",
    available: "Available",
    heldLabel: "Held",
    reservedLabel: "Reserved",
    unavailable: "This seat is already unavailable.",
    exit: "Exit",
    galley: "Galley",
    ledger: "DB Payment / Refund Ledger",
    noLedger: "No payment ledger found.",
    selectedOnly: "Seat selected. Press Create DB Payment to hold and reserve it.",
    classNames: { Economy: "Economy", Business: "Business", First: "First" }
  }
};

function parseSeat(seatNumber: string) {
  const match = seatNumber.match(/^(\d+)([A-Z]+)$/);
  return { row: match ? Number(match[1]) : 0, letter: match ? match[2] : seatNumber };
}

function columnsFor(model: string, className: SeatClass) {
  if (className === "First") return ["A", null, "D", "G", null, "K"];
  if (className === "Business") {
    if (model.includes("A350") || model.includes("A330")) return ["A", null, "D", "G", null, "K"];
    return ["A", "C", null, "D", "G", null, "H", "K"];
  }
  if (model.includes("777")) return ["A", "B", "C", null, "D", "E", "F", "G", null, "H", "J", "K"];
  if (model.includes("A330")) return ["A", "B", null, "C", "D", "F", "G", null, "H", "J"];
  return ["A", "B", "C", null, "D", "E", "F", null, "H", "J", "K"];
}

function rowGroups(seats: Seat[]) {
  const groups = new Map<number, Seat[]>();
  for (const seat of seats) {
    const parsed = parseSeat(seat.seat_number);
    groups.set(parsed.row, [...(groups.get(parsed.row) ?? []), seat]);
  }
  return Array.from(groups.entries()).sort(([a], [b]) => a - b);
}

function sectionMarker(className: SeatClass, row: number) {
  if (className === "Economy" && (row === 28 || row === 20 || row === 10)) return "exit";
  if (className === "Business" && row === 1) return "galley";
  return null;
}

function makeId() {
  return Math.floor(Date.now() % 1_000_000_000);
}

function SeatsContent() {
  const { locale } = useLocale();
  const t = copy[locale];
  const params = useSearchParams();
  const initialFlightIds = (params.get("flight_ids") ?? params.get("flight_id") ?? "1001")
    .split(",")
    .map((value) => value.trim())
    .filter(Boolean);
  const [flightIds, setFlightIds] = useState(initialFlightIds);
  const [activeLegIndex, setActiveLegIndex] = useState(0);
  const activeFlightId = flightIds[activeLegIndex] ?? "1001";
  const [flight, setFlight] = useState<FlightInfo | null>(null);
  const [seats, setSeats] = useState<Seat[]>([]);
  const [selected, setSelected] = useState<Seat | null>(null);
  const [selectedByFlight, setSelectedByFlight] = useState<Record<string, Seat>>({});
  const [message, setMessage] = useState("");
  const [alert, setAlert] = useState("");
  const [ledger, setLedger] = useState<Ledger | null>(null);
  const [promotions, setPromotions] = useState<Promotion[]>([]);
  const [selectedPromo, setSelectedPromo] = useState("");
  const [form, setForm] = useState({
    user_id: "cust01",
    payment_method: "CARD",
    lookup_booking_id: ""
  });

  const sections = useMemo(
    () =>
      (["First", "Business", "Economy"] as SeatClass[])
        .map((className) => ({ className, seats: seats.filter((seat) => seat.class_name === className) }))
        .filter((section) => section.seats.length > 0),
    [seats]
  );

  async function loadSeats(targetFlightId = activeFlightId) {
    await fetch("/api/flights/hold/release", { method: "POST" });
    const response = await fetch(`/api/flights/seats?flight_id=${targetFlightId}`);
    const json = await response.json();
    setFlight(json.data?.flight ?? null);
    setSeats(json.data?.seats ?? []);
  }

  async function loadLedger(bookingId = form.lookup_booking_id) {
    if (!bookingId) return;
    const response = await fetch(`/api/bookings/ledger?booking_id=${bookingId}`);
    const json = await response.json();
    setLedger(json.data ?? null);
  }

  async function loadPromotions(seat: Seat) {
    const params = new URLSearchParams({
      flight_id: String(seat.flight_id),
      class_name: seat.class_name
    });
    const response = await fetch(`/api/flights/promotions?${params}`);
    const json = await response.json();
    setPromotions(json.data?.promotions ?? []);
    setSelectedPromo("");
  }

  useEffect(() => {
    loadSeats();
  }, []);

  function switchLeg(index: number) {
    const nextFlightId = flightIds[index];
    setActiveLegIndex(index);
    setSelected(selectedByFlight[nextFlightId] ?? null);
    setPromotions([]);
    setSelectedPromo("");
    loadSeats(nextFlightId);
  }

  function chooseSeat(seat: Seat) {
    setSelected(seat);
    setSelectedByFlight((prev) => ({ ...prev, [String(seat.flight_id)]: seat }));
    setMessage(t.selectedOnly);
    loadPromotions(seat);
  }

  async function holdSelectedSeat(seat: Seat) {
    const response = await fetch("/api/flights/hold", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        hold_id: makeId(),
        user_id: form.user_id,
        flight_id: seat.flight_id,
        seat_number: seat.seat_number
      })
    });
    const json = await response.json();
    if (response.status === 409) {
      setAlert(locale === "ko" ? json.message : "The selected seat is already held or reserved.");
      await loadSeats(String(seat.flight_id));
      return false;
    }
    setMessage(`${seat.seat_number} ${t.held}`);
    await loadSeats(String(seat.flight_id));
    return true;
  }

  async function reserve(event: FormEvent) {
    event.preventDefault();
    if (!selected) {
      setAlert(t.selectFirst);
      return;
    }
    const seatsToReserve = flightIds.map((id) => selectedByFlight[id]).filter(Boolean);
    if (seatsToReserve.length !== flightIds.length) {
      setAlert(t.selectAllLegs);
      return;
    }

    const legsForCheckout = [];
    for (const seat of seatsToReserve) {
      const held = await holdSelectedSeat(seat);
      if (!held) return;
      legsForCheckout.push({
        flight_id: seat.flight_id,
        seat_number: seat.seat_number,
        promo_code: seat.flight_id === selected.flight_id ? selectedPromo || undefined : undefined
      });
    }

    const response = await fetch("/api/bookings/reserve-itinerary", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        user_id: form.user_id,
        payment_method: form.payment_method,
        legs: legsForCheckout
      })
    });
    const json = await response.json();
    if (response.status === 409) {
      setAlert(locale === "ko" ? json.message : "One of the selected seats is already held or reserved.");
      await loadSeats();
      return;
    }
    if (!response.ok) {
      setAlert(json.message ?? t.reserveError);
      return;
    }

    const lastBookingId = String(json.data.bookings.at(-1).booking_id);
    setMessage(`${selected.seat_number} ${t.reserved}`);
    setForm((prev) => ({ ...prev, lookup_booking_id: lastBookingId }));
    setSelected(null);
    setSelectedByFlight({});
    setPromotions([]);
    setSelectedPromo("");
    await loadSeats();
    await loadLedger(lastBookingId);
  }

  async function cancelAndRefund() {
    const response = await fetch("/api/bookings/cancel", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ booking_id: Number(form.lookup_booking_id) })
    });
    const json = await response.json();
    if (!response.ok) {
      setAlert(json.message ?? t.reserveError);
      return;
    }
    setMessage(t.refunded);
    await loadSeats();
    await loadLedger(form.lookup_booking_id);
  }

  return (
    <div className="space-y-6">
      {alert && (
        <div className="fixed inset-0 z-20 grid place-items-center bg-slate-900/30 px-4">
          <div className="w-full max-w-md rounded border-2 border-red-500 bg-white p-6 shadow-lg">
            <h2 className="text-lg font-semibold text-red-700">{t.conflictTitle}</h2>
            <p className="mt-3 text-sm leading-6 text-slate-700">{alert}</p>
            <button onClick={() => setAlert("")} className="mt-5 rounded bg-red-600 px-4 py-2 text-sm font-semibold text-white">
              {t.confirm}
            </button>
          </div>
        </div>
      )}

      <section className="rounded border border-slate-200 bg-white p-5">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <h1 className="text-2xl font-semibold text-navy">{t.title}</h1>
            {flight && (
              <p className="mt-2 text-sm text-slate-600">
                {flight.airline_name} {flight.flight_number} · {flight.dep_airport} → {flight.arr_airport} · {flight.model}
              </p>
            )}
          </div>
          <div className="flex flex-wrap items-end gap-3">
            {flightIds.length > 1 && (
              <div className="flex flex-wrap gap-2">
                {flightIds.map((id, index) => (
                  <button
                    key={id}
                    type="button"
                    onClick={() => switchLeg(index)}
                    className={`rounded border px-3 py-2 text-sm font-semibold ${
                      activeLegIndex === index ? "border-navy bg-navy text-white" : "border-slate-300 bg-white text-slate-700"
                    }`}
                  >
                    {t.leg} {index + 1}: {id}
                    {selectedByFlight[id] ? ` / ${selectedByFlight[id].seat_number}` : ""}
                  </button>
                ))}
              </div>
            )}
            <label className="text-sm font-medium text-slate-700">
              {t.flightId}
              <input
                value={activeFlightId}
                onChange={(event) => {
                  const next = event.target.value;
                  setFlightIds([next]);
                  setActiveLegIndex(0);
                }}
                className="mt-2 w-28 rounded border border-slate-300 px-3 py-2"
              />
            </label>
            <button onClick={() => loadSeats()} className="rounded bg-navy px-4 py-2 text-sm font-semibold text-white">
              {t.load}
            </button>
          </div>
        </div>
        <div className="mt-4 flex flex-wrap gap-3 text-xs text-slate-600">
          {flightIds.length > 1 && <span className="font-medium text-navy">{t.connectingNotice}</span>}
          <span className="inline-flex items-center gap-2"><span className="h-3 w-3 rounded border border-slate-300 bg-white" /> {t.available}</span>
          <span className="inline-flex items-center gap-2"><span className="h-3 w-3 rounded border border-amber-300 bg-amber-100" /> {t.heldLabel}</span>
          <span className="inline-flex items-center gap-2"><span className="h-3 w-3 rounded border border-slate-300 bg-slate-200" /> {t.reservedLabel}</span>
          {message && <span className="font-medium text-emerald-700">{message}</span>}
        </div>
      </section>

      <div className="grid gap-6 lg:grid-cols-[1fr_380px]">
        <section className="overflow-auto rounded border border-slate-200 bg-white p-5">
          <div className="mx-auto min-w-[620px] max-w-4xl rounded-[48px] border-2 border-slate-300 bg-slate-50 px-8 py-8">
            <div className="mx-auto mb-8 h-14 w-40 rounded-t-full border-x-2 border-t-2 border-slate-300 bg-white" />
            <div className="space-y-8">
              {sections.map((section) => {
                const columns = columnsFor(flight?.model ?? "", section.className);
                return (
                  <div key={section.className}>
                    <div className="mb-3 flex items-center justify-between border-b border-slate-200 pb-2">
                      <h2 className="text-sm font-semibold uppercase tracking-wide text-navy">{t.classNames[section.className]}</h2>
                      <span className="text-xs text-slate-500">{columns.filter(Boolean).join(" ")}</span>
                    </div>
                    <div className="space-y-2">
                      {rowGroups(section.seats).map(([row, rowSeats]) => {
                        const byLetter = new Map(rowSeats.map((seat) => [parseSeat(seat.seat_number).letter, seat]));
                        const marker = sectionMarker(section.className, row);
                        return (
                          <div key={row} className="flex items-center gap-3">
                            <div className="w-8 text-right text-xs font-semibold text-slate-400">{row}</div>
                            <div className="grid flex-1 items-center gap-2" style={{ gridTemplateColumns: `repeat(${columns.length}, minmax(34px, 1fr))` }}>
                              {columns.map((letter, index) => {
                                if (!letter) return <div key={`aisle-${index}`} className="h-9 rounded bg-slate-100" />;
                                const seat = byLetter.get(letter);
                                if (!seat) return <div key={`${row}-${letter}`} className="h-9" />;
                                const disabled = seat.seat_status !== "available";
                                const statusClass =
                                  seat.seat_status === "reserved"
                                    ? "border border-slate-300 bg-slate-200 text-slate-400"
                                    : seat.seat_status === "held"
                                      ? "border border-amber-300 bg-amber-100 text-amber-800"
                                      : selected?.seat_number === seat.seat_number
                                        ? "border border-navy bg-navy text-white"
                                        : "border border-slate-300 bg-white text-slate-700 hover:border-navy hover:text-navy";
                                return (
                                  <button
                                    type="button"
                                    key={seat.seat_number}
                                    disabled={disabled}
                                    title={disabled ? t.unavailable : `${seat.seat_number} $${seat.price}`}
                                    onClick={() => chooseSeat(seat)}
                                    className={`h-9 min-w-9 rounded text-xs font-semibold transition ${statusClass}`}
                                  >
                                    {seat.seat_number}
                                  </button>
                                );
                              })}
                            </div>
                            <div className="w-14 text-xs text-slate-400">{marker === "exit" ? t.exit : marker === "galley" ? t.galley : ""}</div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                );
              })}
            </div>
            <div className="mx-auto mt-8 h-10 w-56 rounded-b-full border-x-2 border-b-2 border-slate-300 bg-white" />
          </div>
        </section>

        <aside className="space-y-4">
          <form onSubmit={reserve} className="rounded border border-slate-200 bg-white p-5">
            <h2 className="text-lg font-semibold text-navy">{t.payment}</h2>
            <p className="mt-2 text-sm text-slate-500">
              {t.selectedSeat}: {selected ? `${selected.seat_number} / ${selected.class_name} / $${selected.price}` : t.none}
            </p>
            {selected && (
              <section className="mt-4 rounded border border-slate-200 bg-slate-50 p-3">
                <h3 className="text-sm font-semibold text-navy">{t.promos}</h3>
                {promotions.length === 0 ? (
                  <p className="mt-2 text-xs text-slate-500">{t.noPromos}</p>
                ) : (
                  <div className="mt-3 space-y-2">
                    <label className="flex items-center gap-2 text-sm text-slate-700">
                      <input
                        type="radio"
                        name="promo"
                        checked={selectedPromo === ""}
                        onChange={() => setSelectedPromo("")}
                      />
                      {t.applyNone}
                    </label>
                    {promotions.map((promo) => (
                      <label key={promo.promo_code} className="flex items-start gap-2 text-sm text-slate-700">
                        <input
                          type="radio"
                          name="promo"
                          className="mt-1"
                          checked={selectedPromo === promo.promo_code}
                          onChange={() => setSelectedPromo(promo.promo_code)}
                        />
                        <span>
                          <span className="font-semibold text-navy">{promo.promo_code}</span>
                          <span className="ml-2 text-emerald-700">-{promo.discount_percent}%</span>
                          <br />
                          <span className="text-xs text-slate-500">{promo.description}</span>
                        </span>
                      </label>
                    ))}
                  </div>
                )}
                <p className="mt-3 text-sm font-semibold text-navy">
                  {t.estimated}: $
                  {(
                    selected.price *
                    (1 - (promotions.find((promo) => promo.promo_code === selectedPromo)?.discount_percent ?? 0) / 100)
                  ).toLocaleString()}
                </p>
              </section>
            )}
            <div className="mt-5 space-y-3">
              <label className="block text-sm font-medium text-slate-700">
                user_id
                <input
                  value={form.user_id}
                  onChange={(event) => setForm((prev) => ({ ...prev, user_id: event.target.value }))}
                  className="mt-1 w-full rounded border border-slate-300 px-3 py-2"
                />
              </label>
              <label className="block text-sm font-medium text-slate-700">
                payment_method
                <select
                  value={form.payment_method}
                  onChange={(event) => setForm((prev) => ({ ...prev, payment_method: event.target.value }))}
                  className="mt-1 w-full rounded border border-slate-300 px-3 py-2"
                >
                  <option value="CARD">CARD</option>
                  <option value="TRANSFER">TRANSFER</option>
                  <option value="CASH">CASH</option>
                </select>
              </label>
              <label className="block text-sm font-medium text-slate-700">
                {t.lookupBooking}
                <input
                  value={form.lookup_booking_id}
                  onChange={(event) => setForm((prev) => ({ ...prev, lookup_booking_id: event.target.value }))}
                  className="mt-1 w-full rounded border border-slate-300 px-3 py-2"
                />
              </label>
            </div>
            <p className="mt-3 text-xs text-slate-500">{t.autoIds}</p>
            <button className="mt-5 w-full rounded bg-navy px-4 py-2.5 text-sm font-semibold text-white">
              {flightIds.length > 1 ? t.checkout : t.reserve}
            </button>
            <button type="button" onClick={cancelAndRefund} className="mt-2 w-full rounded border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700">
              {t.cancelRefund}
            </button>
            <button type="button" onClick={() => loadLedger()} className="mt-2 w-full rounded border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">
              {t.lookup}
            </button>
          </form>

          <section className="rounded border border-slate-200 bg-white p-5">
            <h2 className="text-lg font-semibold text-navy">{t.ledger}</h2>
            {!ledger?.booking ? (
              <p className="mt-3 text-sm text-slate-500">{t.noLedger}</p>
            ) : (
              <div className="mt-3 space-y-2 text-sm text-slate-700">
                <p>Booking #{ledger.booking.booking_id} · {ledger.booking.status}</p>
                <p>Seat {ledger.booking.seat_number} · Ticket #{ledger.booking.ticket_id}</p>
                <p>Payment #{ledger.booking.payment_id} · {ledger.booking.payment_method} · {ledger.booking.payment_status}</p>
                <p className="font-semibold text-navy">${Number(ledger.booking.amount ?? 0).toLocaleString()}</p>
                {ledger.refunds.map((refund) => (
                  <div key={refund.refund_id} className="rounded border border-red-100 bg-red-50 p-3 text-red-700">
                    Refund #{refund.refund_id} · Payment #{refund.payment_id} · ${Number(refund.refund_amount).toLocaleString()}
                  </div>
                ))}
              </div>
            )}
          </section>
        </aside>
      </div>
    </div>
  );
}

export default function SeatsPage() {
  const { locale } = useLocale();
  return (
    <Suspense fallback={<div className="rounded border border-slate-200 bg-white p-5 text-sm text-slate-600">{copy[locale].loading}</div>}>
      <SeatsContent />
    </Suspense>
  );
}
